rate/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm

urlpatterns = [
   path('', views.home, name='home'),
   path('profile/',views.profile,name='profile'),
   path('register/',views.register,name='register'),
   path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm,extra_context={'title': 'Login'}), name='login'),
   path('logout/', views.logout_view, name='logout'),
   path('profile/update',views.edit_profile,name='update_profile'),
   path('project/new',views.new_project,name='new_project'),
   path('project/view/<int:id>',views.project_view,name='project_view'),
   path('search/',views.search,name="search"),
   # Extra views
   path('api/profiles/',views.ProfileList.as_view()),
   path('api/projects/',views.ProjectList.as_view())
]

rated/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('rate.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

rate/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
   '''
   Holds user's profile data.
   '''

   user = models.OneToOneField(User, on_delete=models.CASCADE)
   avatar = models.ImageField(upload_to='avatars/',null=True,default='default.jpg')
   bio = models.TextField(max_length=140,null=True)

   def __str__(self):
      return self.user.username

class Project(models.Model):
   '''
   Model to hold user's project data.
   '''

   author = models.ForeignKey(Profile, on_delete=models.CASCADE)
   name = models.CharField(max_length=70)
   description = models.TextField(max_length=140)
   img = models.ImageField(upload_to='projects/')
   time_published = models.DateField(auto_now=True)
   link = models.CharField(max_length=140)
   
   def __str__(self):
      return self.name
      
class Rating(models.Model):
   '''
   Model to hold projects' ratings
   '''
   review = models.CharField(max_length=140,default='')
   design = models.IntegerField(default=0)
   usability = models.IntegerField(default=0)
   content = models.IntegerField(default=0)
   rated = models.ForeignKey(Project, on_delete=models.CASCADE)
   rated_by = models.ForeignKey(Profile, on_delete=models.CASCADE)

   def __str__(self):
      return self.rated.name

class Contact(models.Model):
   '''
   Contact class to hold the different contact details of a user
   '''
   facebook = models.CharField(max_length=70,null=True,default='#')
   twitter = models.CharField(max_length=70,null=True,default='#')
   instagram = models.CharField(max_length=70,null=True,default='#')
   github = models.CharField(max_length=70,null=True,default='#')
   prfl = models.OneToOneField(Profile, on_delete=models.CASCADE)

   def __str__(self):
      return self.prfl.user.username

rate/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from .models import Profile,Project,Contact,Rating

class Registration(UserCreationForm):
   '''
   User registration form.
   '''
   username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username'}))
   email= forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}), max_length=64)
   password1= forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
   password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))


   class Meta(UserCreationForm.Meta):
      model = User
      fields = UserCreationForm.Meta.fields + ("email","username","password1")


class LoginForm(AuthenticationForm):
   '''
   User login form.
   '''
   
   username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username'}))
   password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))

   class Meta:
      model = User
      fields = ['username','password']

class ProfileUpdateForm(forms.ModelForm):
   '''
   User profile update form.
   '''

   class Meta:
      model = Profile
      fields = ['avatar', 'bio']
      widgets = {
         'bio': forms.TextInput(attrs={'placeholder': 'Enter new bio'})
      }

class ContactUpdateForm(forms.ModelForm):
   '''
   User contact update form.
   '''
   facebook = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Facebook Linkgcm '}))
   twitter = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Twitter Link'}))
   instagram = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Instagram Link'}))
   github = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Github Link'}))
   class Meta:
      model = Contact
      fields = ['facebook','twitter','instagram','github']

class ProjectForm(forms.ModelForm):
   '''
   New project creation form.
   '''

   name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Project Title'}))
   description = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Description'}))
   link = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Project Link'}))
   description = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Project Description'}))

   class Meta:
      model = Project
      fields = ['name','img','description','link']


class RatingForm(forms.ModelForm):
   '''
   Ratings form
   '''

   RATINGS = (
      (1,''),
      (2,''),
      (3,''),
      (4,''),
      (5,''),
   )

   design = forms.ChoiceField(choices=RATINGS, widget=forms.RadioSelect())
   usability = forms.ChoiceField(choices=RATINGS, widget=forms.RadioSelect())
   content = forms.ChoiceField(choices=RATINGS, widget=forms.RadioSelect())  
   review = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Give a review'})) 
   class Meta:
      model = Rating
      fields = ['design','usability','content','review']

rate/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from .models import Profile,Project,Rating,Contact
from .forms import Registration,LoginForm,ProfileUpdateForm,ContactUpdateForm,ProjectForm,RatingForm
from django.db.models import Sum
from rest_framework.response import Response
from rest_framework.views import APIView
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from .serializer import *


# Create your views here.
def home(request):

   title = "Accolade"
   projects = Project.objects.all()

   context = {
      'projects': projects,
      'title': title
   }

   return render(request, 'rate/home.html', context)


def search(request):
   
   if 'project_search' in request.GET and request.GET["project_search"]:
      searched = request.GET.get("project_search")
      if searched:
         projects = Project.objects.filter(name=searched).all()
         title = f"You searched for {searched}"

   context = {
      'projects': projects,
      'title': title,
      'searched': searched
   }

   return render(request, 'rate/search.html', context)

@login_required(login_url='register')
def profile(request):
   user = request.user
   print(user)

   projects = Project.objects.filter(author=user.profile)

   title = f'{user.first_name} {user.last_name}'
   context = {
      'title': title,
      'projects': projects
   }

   return render(request,'rate/profile.html',context)



def register(request):

   title = 'Sign Up'

   if request.method == 'POST':
      form = Registration(request.POST)
      if form.is_valid():
         form.save()
         username = form.cleaned_data.get('username')
         raw_password = form.cleaned_data.get('password1')
         user = authenticate(username=username,password=raw_password)
         login(request,user)
         profile = Profile(user=user)
         profile.save()

         return redirect('home')
   else:
      form = Registration()

   context = {
      'title': title,
      'form': form
   }

   return render(request,'rate/register.html',context)

@login_required(login_url='register')
def edit_profile(request):

   title = f"Edit Profile | {request.user.first_name} {request.user.last_name}" 

   user = request.user

   if request.method == 'POST':
      form = ProfileUpdateForm(request.POST,request.FILES,instance=user.profile)
      contact_form = ContactUpdateForm(request.POST)
      if form.is_valid() and contact_form.is_valid():
         form.save()
         contact = contact_form.save(commit=False)
         contact.prfl = user.profile
         contact.save()
         return redirect('profile')
   else:
      form = ProfileUpdateForm(instance=user.profile)
      contact_form = ContactUpdateForm()

   context = {
      'form': form,
      'contact_form': contact_form,
      'title': title
   }

   return render(request,'rate/update_profile.html',context)

@login_required(login_url='register')
def new_project(request):

   user = request.user

   title = 'New Project'

   if request.method == 'POST':
      form = ProjectForm(request.POST,request.FILES)
      if form.is_valid():
         project = form.save(commit=False)
         project.author = user.profile
         project.save()
         return redirect('home')
   else:
      form = ProjectForm()

   context = {
      'form': form,
      'title': title
   }

   return render(request, 'rate/new_project.html',context)

@login_required(login_url='register')
def project_view(request,id):

   user = request.user

   project = Project.objects.filter(pk=id).first()

   ratings = Rating.objects.filter(rated=project)

   if ratings:
      average = ((ratings.aggregate(Sum('design'))['design__sum'])/ratings.count() + 
      ratings.aggregate(Sum('usability'))['usability__sum']/ratings.count() + 
      ratings.aggregate(Sum('content'))['content__sum']/ratings.count()) / 3
   else:
      average = '0.0'

   title = f'{project.name} by {project.author.user.first_name}'

   if request.method == 'POST':
      form = RatingForm(request.POST)
      rated = Rating.objects.filter(rated=project,rated_by=user.profile)
      if form.is_valid() and not rated:
         rating = form.save(commit=False)
         rating.rated_by = user.profile
         rating.rated = project
         rating.save()
         return redirect('project_view', id=id)
      elif form.is_valid() and rated:
         rated.delete()
         rating = form.save(commit=False)
         rating.rated_by = user.profile
         rating.rated = project
         rating.save()
         return redirect('project_view', id=id)
   else:
      form = RatingForm()

   context = {
      'title': title,
      'project': project,
      'ratings': ratings,
      'average': average,
      'form': form,
   }

   return render(request,'rate/project_view.html',context)

@login_required(login_url='register')
def logout_view(request):
   logout(request)
   return redirect('login')



class ProfileList(APIView):
    def get(self, request, format=None):
        all_profiles = Profile.objects.all()
        serializers = ProfileSerializer(all_profiles, many=True)
        return Response(serializers.data)

class ProjectList(APIView):
    def get(self, request, format=None):
        all_projects = Project.objects.all()
        serializers = ProjectSerializer(all_projects, many=True)
        return Response(serializers.data)

rate/templates/rate/home.html
{% extends "rate/layout.html" %}
{% load static %}

{% block content %}
{% include "rate/nav.html" %}

<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
   integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

{% if user.is_authenticated %}
<hr>
<a href="{% url 'new_project' %}">
   <button class='btn btn-dark'><i class="fas fa-plus-circle"></i> Add Project</button>
</a>


{% endif %}
<div class="container">
<div class="row">
   {% for prjct in projects  %}
   <div class="col-md-6">
      <div class="card">
         <a href="{% url 'project_view' prjct.id %}">
            <div style="text-align: center;" class="card-title">
               <img style="border-radius: 100%" width="20%;" src="{{ prjct.author.avatar.url }}" alt="">
               <h4 style="color: #000;">{{ prjct.name }}</h4>
            </div>
            <div class="card-body">
               <img width="100%;" src="{{ prjct.img.url }}" alt="{{ prjct.name }}">
            </div>
            <div class="project-desc">
               <div class="author">
                  <p>{{ prjct.author.user.first_name }} {{ prjct.author.user.last_name }}</p>
               </div>
            </div>
      </div>
   </div>
   </a>
   {% endfor %}
</div>
</div>
<style>
   .card {
      width: 80%;
      min-height: 460px;
      margin-top: 60px;
      box-shadow: 0px 8px 60px -10px rgba(13, 28, 39, 0.6);
      background: #fff;
      border-radius: 12px;
      max-width: 700px;
      position: relative;
   }
</style>
<script>
   $('.dropdown-toggle').dropdown()
</script>

{% endblock %}

rate/templates/rate/layout.html
{% load static %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
   <link rel="stylesheet" href="https://bootswatch.com/4/cosmo/bootstrap.min.css">
   <title>Accolade</title>
   <style>
   body{
      background-image: radial-gradient(circle, white, black)
   }
   </style>
</head>
<body>

   {% block content %}
   
      
   {% endblock content %}
   
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
   <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

rate/templates/rate/nav.html
{% load static %}
<link href="https://fonts.googleapis.com/css?family=Permanent+Marker&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<nav style="display:flex; flex-direction: right; justify-content: space-around;">
<img width=70px; src="https://png.pngtree.com/element_pic/16/11/02/bd886d7ccc6f8dd8db17e841233c9656.jpg">
   <div>
      <a href="{% url 'home' %}">
         <h1 style="font-family: 'Permanent Marker', cursive; text-decoration: none; color:#fff;">Accolade</h1>
      </a>
   </div>
   <div style="padding-top: 2%;" class="searchform">
      <form action="{% url 'search' %}" method="get">
         {% csrf_token %}
         <input type="text" name="project_search" id="prjct-search" placeholder="Search for a project">
      </form>
   </div>
   {% if user.is_authenticated %}
   <div style="padding-top: 2%;">
      <a class='prfl-icon' href="{% url 'profile' %}">
         <i style="color: #fff; font-size: 2em;" class="fas fa-user-circle"></i>
      </a>
      {% else %}
      <a href="{% url 'login' %}">
            <button style="margin-top: 20%;" class="btn btn-dark" type="submit">Log In</button>
      </a>
   </div>

   {% endif %}

</nav>

<style>
   nav {
      background-color: #051526;
   }
</style>

rate/templates/rate/new_project.html
{% extends "rate/layout.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   <div class="nav-bg">
      {% include "rate/nav.html" %}
   </div>
<div class="row">
   <div class="col-md-3"></div>
   <div class="col-md-8">
         <div class="card">
               <form style="margin-top: 3%;" action="" method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button class="btn btn-secondary" type="submit">Publish</button>
               </form>
            </div>
   </div>
   <div class="col-md-1"></div>
</div>
<style>
      .card {
         width: 80%;
         min-height: 460px;
         margin-top: 60px;
         box-shadow: 0px 8px 60px -10px rgba(13, 28, 39, 0.6);
         background: rgba(255, 255, 255, 0.417);
         border-radius: 12px;
         max-width: 700px;
         position: relative;
         text-align: center;
      }
   </style>
  
{% endblock content %}

rate/templates/rate/profile.html
{% extends "rate/layout.html" %}

{% block content %}

   <div class="nav-bg">
      {% include "rate/nav.html" %}
   </div>
   
      <div style="text-align: center; background-color:rgba(255, 255, 255, 0.678);" class="jumbotron">
         <div class="avatar-lg">
            <img style="border-radius: 100%" width="10%;"  src="{{ user.profile.avatar.url }}" alt="">
         </div>
         <div class="prfl-desc">
            <div class="bio">
               <h1>{{ user.first_name }} {{ user.last_name }}</h1>
               <p>@{{ user.username }}</p>
               <h3 class="bio-txt">{{ user.profile.bio }}</h3>
            </div>
            <br>
            <div class="contacts">
               <div class="email">
                  <a href="/{{ user.email }}" clci>{{ user.email }}</a>
               </div>
               <div class="social">
                  <a href="">
                     <i class="fab fa-facebook-f"></i>
                  </a>
                  <a href="">
                     <i class="fab fa-twitter"></i>
                  </a>
                  <a href="">
                     <i class="fab fa-instagram"></i>
                  </a>
                  <a href="">
                     <i class="fab fa-github"></i>
                  </a>
               </div>
               <br>
               <a href="{% url 'update_profile' %}">
                  <button class='btn btn-dark'>Edit Profile</button>
               </a>
               <a href="{% url 'logout' %}">
                  <button class='btn btn-dark'>Logout</button>
               </a>
            </div>
         </div>
      </div>
      <div class="container">
            <div class="row">
               {% for prjct in projects  %}
               <div class="col-md-6">
                  <div class="card">
                     <a href="{% url 'project_view' prjct.id %}">
                        <div class="card-title">
                           <img style="border-radius: 100%" width="20%;" src="{{ prjct.author.avatar.url }}" alt="">
                           <h4 style="color:#000;">{{ prjct.name }}</h4>
                        </div>
                        <div class="card-body">
                           <img width="100%;" src="{{ prjct.img.url }}" alt="{{ prjct.name }}">
                        </div>
                        <div class="project-desc">
                           <div class="author">
                              <p>{{ prjct.author.user.first_name }} {{ prjct.author.user.last_name }}</p>
                           </div>
                        </div>
                  </div>
               </div>
               </a>
               {% endfor %}
            </div>
            </div>
            
<style>
   i {
      font-size: 1.3em;
      color: #000;
   }
   .card {
         width: 80%;
         min-height: 460px;
         margin-top: 60px;
         box-shadow: 0px 8px 60px -10px rgba(13, 28, 39, 0.6);
         background: rgba(255, 255, 255, 0.417);
         border-radius: 12px;
         max-width: 700px;
         position: relative;
         text-align: center;
      }
</style>

{% endblock content %}

rate/templates/rate/project_view.html
{% extends "rate/layout.html" %}
{% load static %}

{% block content %}
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
   integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<div class="nav-bg">
   {% include "rate/nav.html" %}
</div>
<br>
<div class="row">
   <div class="col-md-6">
         <div style="display:flex; flex-direction: right;">
               <img style="border-radius: 100%" width="20%;" src="{{ project.author.avatar.url }}" alt="">
               <h1 style="color: #fff;" class="title">{{ project.name }} <a href="{{project.link}}"><i style="font-size: 0.5em; color: #000;" class="fas fa-external-link-alt"></i></a></h1>
            </div>
            <br>
            
            <img width="100%;" src="{{ project.img.url }}" alt="">
            
            <p>{{ project.author.user.first_name }} {{ project.author.user.last_name }}</p>
            <div class="project-meta">
            
               <h5 style="color: #fff;">{{ project.time_published|date:'M d, Y' }}</h5>
            </div>
   </div>

   <div class="col-md-6">
               <div class="overall">
                  <i class="fas fa-star"></i>
                  <div>
                     <h1>{{ average|floatformat }}</h1>
                  </div>
               </div>
            
         <div class="description">
         
            <p>{{ project.description }}</p>
         </div>
         <div class="reviews">
            {% for rating in ratings  %}
            <div class="prjct-review">
               <div class="author">
                  <div>
                     <img width="100px" style="border-radius: 100%" src="{{ rating.rated_by.avatar.url }}" alt="">
                  </div>
                  <p>{{ rating.rated_by.user.username }}</p>
               </div>
               <p class="the-review">{{ rating.review }}</p>
               <div class="ratings">
                  <div>
                     <i class="fas fa-star"></i>
                     <div>
                        <h1>{{ rating.design }}</h1>
                     </div>
                  </div>
                  <div>
                     <i class="fas fa-star"></i>
                     <div>
                        <h1>{{ rating.usability }}</h1>
                     </div>
                  </div>
                  <div>
                     <i class="fas fa-star"></i>
                     <div>
                        <h1>{{ rating.content }}</h1>
                     </div>
                  </div>
               </div>
            </div>
            {% endfor %}
         </div>
         <div class="rating-form">
            <form action="" method="post">
               {% csrf_token %}
               {{ form.as_p }}
            </form>
         </div>
      </div>
   </div>



<style>
   .rating-form {
      padding: 1% 0;
   }

   ul {
      padding: 0;
   }

   li {
      display: inline-block;
   }

   li label>input {
      display: none;
   }

   li#id_design label>input:checked {
      font-family: "Font Awesome 5 Free";
      content: '\f005';
      display: inline-block;
      color: rgba(#333, 0.2);
      font-weight: 900;
   }

   input:checked ::before {
      font-family: "Font Awesome 5 Free";
      content: '\f005';
      display: inline-block;
      color: rgba(#333, 0.2);
      font-weight: 900;
   }

   li>label::before {
      cursor: pointer;
      font-family: "Font Awesome 5 Free";
      content: '\f005';
      display: inline-block;
      color: rgba(#333, 0.2);
      font-weight: 900;
   }

   li>label:hover::before,
   li>label:hover~label::before {
      cursor: pointer;
      font-family: "Font Awesome 5 Free";
      content: '\f005';
      display: inline-block;
      color: clr(scndry);
      font-weight: 900;
   }
</style>

{% endblock content %}

rate/templates/rate/register.html
{% extends "rate/layout.html" %}
{% load static %}

{% block content %}

   <div class="nav-bg">
      {% include "rate/nav.html" %}
   </div>
<div class="row">
   <div class="col-md-3"></div>
   <div class="col-md-8">
     
      <div class="card">
         <form style="margin-top: 3%;" action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-secondary" type="submit">Sign Up</button>
         </form>
         <p class="auth-switch">Have an account? <a href="{% url 'login' %}">Log In</a></p>
      </div>
   </div>
   
   <div class="col-md-2">

   </div>

</div>
   <style>
         .card {
            width: 80%;
            min-height: 460px;
            margin-top: 60px;
            box-shadow: 0px 8px 60px -10px rgba(13, 28, 39, 0.6);
            background: rgba(255, 255, 255, 0.417);
            border-radius: 12px;
            max-width: 700px;
            position: relative;
            text-align: center;
         }
      </style>
  
{% endblock content %}

rate/templates/rate/search.html
{% extends "rate/layout.html" %}
{% load static %}
{% include "rate/nav.html" %}
{% block content %}
   
   {% if user.is_authenticated %}
      <div class="container new-post">
         <a href="{% url 'new_project' %}">
            <button class='btn'><i class="fas fa-plus-circle"></i> Add Project</button>
         </a>
      </div>     
   {% endif %}

   <div class="search-notif">
      {% if projects %}
         <h1>Your search for <span>{{ searched }}</span> returned:</h1>  
      {% else %}
         <h1>There are no search results for <span>{{ searched }}</span></h1>
      {% endif %}
   </div>
   
   <div class="project-pane">
      {% for prjct in projects  %}
         <a href="{% url 'project_view' prjct.id %}">
            <div class="project-card">
               <div class="image">
                  <img src="{{ prjct.img.url }}" alt="{{ prjct.name }}">
               </div>
               <div class="project-desc">
                  <div class="author">
                     <div class="avatar-sm">
                        <img src="{{ prjct.author.avatar.url }}" alt="">
                     </div>
                     <p>{{ prjct.author.user.first_name }} {{ prjct.author.user.last_name }}</p>
                  </div>
                  <h4>{{ prjct.name }}</h4>
                  <div class="languages">
                     {% for lng in prjct.language.all  %}
                       <p>#{{ lng.language }}</p>
                     {% endfor %}
                  </div>

               </div>        
            </div>        
         </a>
      {% endfor %}
   </div>

  
{% endblock content %}

rate/templates/rate/update_profile.html
{% extends "rate/layout.html" %}
{% load static %}

{% block content %}

   <div class="nav-bg">
      {% include "rate/nav.html" %}
   </div>
<div class="row">
   <div class="col-md-3"></div>
   <div class="col-md-8">
         <div class="card">
               <form style="margin-top: 3%; padding-left: 10%;" action="" method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="form-group">
                     {{ form.as_p }}
                  </div>
                  <div class="form-group">
                     {{ contact_form.as_p }}
                  </div>
                  <button class="btn btn-secondary" type="submit">Update Profile</button>
               </form>
            </div>
   </div>
   
   <div class="col-md-2"></div>
</div>
   
<style>
      .card {
         width: 80%;
         min-height: 460px;
         margin-top: 60px;
         box-shadow: 0px 8px 60px -10px rgba(13, 28, 39, 0.6);
         background: #fff;
         border-radius: 12px;
         max-width: 700px;
         position: relative;
      }
   </style>
{% endblock content %}